# Guest OS timezone
timezone: Europe/Berlin

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual host name
host_name: sphann.intelliad.dev

# Virtual machine name
machine_name: services-intelliad

# Virtual machine IP - SHOULD NOT BE USED ANYWHERE ELSE
ip: 192.168.83.10

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 512

# Environment variables
application_env: development

# path to !BUILT! Backend dir (will be mounted)
path_to_backend: /Users/jsphann/Codez/intelliad_backend/trunk/intelliad_backend
